name: DB Backup
on:
  schedule:
    - cron: '0 2 * * *' # 02:00 UTC nightly
  workflow_dispatch:
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
        
      - name: Install pg_dump & aws
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          pip install awscli
          
      - name: Backup
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: bash scripts/db-backup.sh
