name: CI

on:
  pull_request:
    branches: [main, prod, staging, dev]
  push:
    branches: [main, prod, staging, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 10.14.0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Run audit pack
        id: audit-pack
        run: pnpm audit:all
        continue-on-error: false
        
      - name: Run idempotency tests
        id: idempotency-tests
        run: pnpm test:idempotency || true  # allow pass in warn mode; flip to strict later
        continue-on-error: true
        
      - name: Build verification
        id: build-verification
        run: pnpm run build:netlify
        continue-on-error: false
        
      - name: Check build artifacts
        run: |
          echo "Checking build artifacts..."
          if [ -d ".next" ]; then
            echo "✅ Next.js build directory exists"
            ls -la .next/
          else
            echo "❌ Next.js build directory missing"
            exit 1
          fi
          
      - name: Summary
        run: |
          echo "## CI Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Audit Pack**: ${{ steps.audit-pack.outcome }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Idempotency Tests**: ${{ steps.idempotency-tests.outcome }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Verification**: ${{ steps.build-verification.outcome }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Next Steps" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.audit-pack.outcome }}" != "success" ]; then
            echo "- Fix audit issues before merging" >> $GITHUB_STEP_SUMMARY
          fi
          if [ "${{ steps.idempotency-tests.outcome }}" != "success" ]; then
            echo "- Review idempotency test results" >> $GITHUB_STEP_SUMMARY
          fi
          if [ "${{ steps.build-verification.outcome }}" != "success" ]; then
            echo "- Fix build errors before merging" >> $GITHUB_STEP_SUMMARY
          fi